# Generated by Django 4.1.4 on 2022-12-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('text_order', models.TextField(max_length=1000)),
                ('image', models.ImageField(max_length=254, null=True, upload_to='')),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
